import { DecisionCode, DenyCode } from "../types/decision";

const KNOWN = new Set<DecisionCode>([
  "ALLOW_MINIMAL_PROOF_VALID",
  "DENY_SCHEMA_MISSING_FIELD",
  "DENY_SCHEMA_UNKNOWN_FIELD",
  "DENY_SCHEMA_TYPE_MISMATCH",
  "DENY_POLICY_UNSUPPORTED_VERSION",
  "DENY_POLICY_UNKNOWN_PREDICATE",
  "DENY_POLICY_MINIMIZATION_VIOLATION",
  "DENY_POLICY_PURPOSE_MISMATCH",
  "DENY_BINDING_NONCE_REPLAY",
  "DENY_BINDING_HASH_MISMATCH",
  "DENY_BINDING_AUDIENCE_MISMATCH",
  "DENY_BINDING_EXPIRED",
  "DENY_CRYPTO_VERIFY_FAILED",
  "DENY_CRYPTO_UNSUPPORTED_ALG",
  "DENY_CRYPTO_KEY_STATUS_INVALID",
  "DENY_CREDENTIAL_REVOKED",
  "DENY_RATE_LIMIT_EXCEEDED",
  "DENY_REAUTH_REQUIRED",
  "DENY_JURISDICTION_INCOMPATIBLE",
  "DENY_INTERNAL_SAFE_FAILURE",
]);

export function mapToDeny(code?: string): DenyCode {
  if (!code) return "DENY_INTERNAL_SAFE_FAILURE";
  return KNOWN.has(code as DecisionCode)
    ? (code as DenyCode)
    : "DENY_INTERNAL_SAFE_FAILURE";
}
